
#!/usr/bin/python

''' Problem 2 - Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

import sys

#a and b are the first two number in the fib sequence
a = 0
b = 1
#c is the current number we're checking
c = 0
sum = 0
while c < 4000000:
    c = a + b
    if(c % 2 == 0):#current number is even
        sum += c
    a = b
    b = c
#end while
print "sum: " + str(sum)
